### PR TITLE
Version Update

### PR DESCRIPTION
**Pull request by ravindu01manoj**

### CODE REVIEW

**Comment by Qurban11** [comment]
How to install more options

**Comment by ravindu01manoj** [comment]
> How to install more options

https://github.com/ravindu01manoj/Sew-Queen/wiki/Extrenal-Commands

**Comment by Qurban11** [comment]
Sir please help tell me how to use 18+ command and also tell me is
kingraviya mode still available or not thank you ❤️

**Comment by ravindu01manoj** [comment]
> Sir please help tell me how to use 18+ command and also tell me is kingraviya mode still available or not thank you 


[Xnxx Download Bot](https://github.com/ravindu01manoj/xnxx-dl-wabot.git) <== Deploy This Wa Bot For 18+ Video Download

**Pull request merged**
